mindmap
  root((Tools))
    Time & Math
      get_current_time
      add
      multiply
      divide
    Flight Info
      show_flight_details
      show_flight_delay
      show_flight_cancellation
      show_rebooking_options
      show_overbooking_offer
    Airport Services
      show_map
      show_destination_info
      search_knowledge_base
    In-Flight
      show_seat_management
      show_meal_preference
      show_checked_bags
      show_wifi
    Weather
      show_weather
